// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using escola.Data;

namespace escola.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200831174440_EscolaInicial")]
    partial class EscolaInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("escola.Models.Aluno", b =>
                {
                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("TurmastituloDaTurma")
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("dataDeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("matricula")
                        .HasColumnType("int");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nome");

                    b.HasIndex("TurmastituloDaTurma");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("escola.Models.Turma", b =>
                {
                    b.Property<string>("tituloDaTurma")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("idadeMedia")
                        .HasColumnType("int");

                    b.Property<int>("qtdDeAlunos")
                        .HasColumnType("int");

                    b.HasKey("tituloDaTurma");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("escola.Models.Aluno", b =>
                {
                    b.HasOne("escola.Models.Turma", "Turmas")
                        .WithMany()
                        .HasForeignKey("TurmastituloDaTurma");
                });
#pragma warning restore 612, 618
        }
    }
}
